spring.application.name=apiproyectodaw

# 🔒 Seguridad HTTP básica (puedes dejarlo activo si usas login)
spring.security.user.name=admin
spring.security.user.password=admin123

# 📁 Configuración para la carga de archivos
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB
file.upload-dir=./uploads

# ❌ 🔌 Desactivar conexión JDBC
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
